### ISSUE TITLE
Need to display both tag and name in tagged_menu

### ISSUE THREAD

**Issue by substring** [BashGui/easybashgui#7]
Hi,

I'm trying to convert a script (I didn't write) to work on both shell and X using EBG. There is a small thing which I'd like to change (or have another function handle it ?) : `tagged_menu`. This function renders an ordered list items, and odd arguments are just the result of the selection, but are never displayed.

Concrete example:
`tagged_menu "line1" "Hello, World!" "line2" "Universe, hear my voice!"` outputs
```
1 Hello, World!
2 Universe, hear my voice!
```
but sadly not like
```
line1 Hello, World!
line2 Universe, hear my voice!
```

So:
- could this be implemented  ?
- can all "dialogs" handle it ? This is probably the limiting factor

I'm thinking about adding a named_menu function, or maybe simply a parameter to tagged_menu (--names for example). Any suggestion ?

**Comment by vaisarger** [comment]
Hi Substring! I'm trying to keep EBG's command line as "easy" as possible. Many features have been requested by users, but I added only few. This not because I'm mean, but because I'm trying to keep EBG as simple as possible.

Your problem can be addressed with few simple code lines: 
tagged_menu "line1" "line1: Hello, World!" "line2" "line2: Universe, hear my voice!"
In fact, you can edit tags just as you want, and I can not see the issue at all.

If I didn't understand what you really need, please, reply and explain a little more... :-)

**Comment by substring** [comment]
I want the ordered list to be output with some id and not a number. Nevermind, months after, I've done it another way.

Thank you.
